---
output:
  html_document:
    toc: true
    toc_float: true
---
<br/>


```{r echo=FALSE}
presentations <- read.csv("birgand_presentations.csv", encoding = "UTF-8")
pres<-presentations[presentations$Prestype == "oral",]
poster<-presentations[presentations$Prestype == "poster",]
nbpres<-nrow(pres);nbposter<-nrow(poster)
```


# Oral Presentations *`r paste0("(",nbpres,")")`*

```{r echo=FALSE, results="asis",comment=FALSE}

years <- unique(pres$Year)[order(unique(pres$Year),decreasing = TRUE)] #Get year list

for (year in years){#years

  tmp_pres <- pres[pres$Year == year,]
    
  cat("*",year,paste0("*(",nrow(tmp_pres),")*"),"\n")

for (i in 1:nrow(tmp_pres)){#line printing loop
  if (tmp_pres[i,]$pdf!=""){linkpdf = paste0("([pdf](presentations_pdf/",as.character(tmp_pres$pdf[i]),"))")}else{linkpdf=""}
  if (tmp_pres[i,]$Speaker!=""){speaker = paste0(" -- ***",as.character(tmp_pres$Speaker[i])," speaker***")}else{speaker = ""}
  cat(paste0("\t"))
  cat("+ ",paste0(tmp_pres[i,]$Authors,". \""),paste0(tmp_pres[i,]$Title),"\"  ",paste0("*",tmp_pres[i,]$Venue,".* ",linkpdf,speaker), "\n", sep = "")
}#line print

  
}#years

```

# Posters *`r paste0("(",nbposter,")")`*

```{r echo=FALSE, results="asis",comment=FALSE}

years <- unique(poster$Year)[order(unique(poster$Year),decreasing = TRUE)] #Get year list

for (year in years){#years

  tmp_pres <- poster[poster$Year == year,]
    
  cat("*",year,paste0("*(",nrow(tmp_pres),")*"),"\n")

for (i in 1:nrow(tmp_pres)){#line printing loop
  if (tmp_pres[i,]$pdf!=""){linkpdf = paste0("([pdf](presentations_pdf/",as.character(tmp_pres$pdf[i]),"))")}else{linkpdf=""}
  if (tmp_pres[i,]$Speaker!=""){speaker = paste0(" -- ***",as.character(tmp_pres$Speaker[i])," speaker***")}else{speaker = ""}
  cat(paste0("\t"))
  cat("+ ",paste0(tmp_pres[i,]$Authors,". \""),paste0(tmp_pres[i,]$Title),"\"  ",paste0("*",tmp_pres[i,]$Venue,".* ",linkpdf,speaker), "\n", sep = "")
}#line print

  
}#years

```

