---
output:
  html_document:
    toc: true
    toc_float: true
---


```{r echo=FALSE,warning=FALSE,message=FALSE}
library(RefManageR)

file_journals_EN <- ReadBib("journal_articles_EN.bibtex")
file_journals_FR <- ReadBib("journal_articles_FR.bibtex")
art_nb_EN <- length(file_journals_EN)
art_nb_FR <- length(file_journals_FR)

```
<br/>

# Refereed Journal Articles *(`r art_nb_EN`)*

```{r echo=FALSE, results="asis",comment=FALSE}
file_journals <- file_journals_EN
dates <- unlist(unique(file_journals$year))[order(unlist(unique(file_journals$year)),decreasing = TRUE)]

# make a list for numbering, but inactive as of October 2017
inc_nb<-art_nb_EN
art_list<-list()
for (date in dates) {
  i=1
  yart_nb<-sum(sapply(file_journals_EN[list(year=date)],length))
  art_list[[date]] <- as.vector((inc_nb):(inc_nb - yart_nb + 1))
  art_list[[length(art_list) + i-1]] <-art_list[[date]]
  inc_nb = inc_nb - yart_nb
}

#Prints references
for (date in dates) {
  cat(paste0("## ",date),"\n")
  print(file_journals[list(year=date)],.opts = list(style="markdown",bib.style ="authoryear" ,max.names =20,dashed=FALSE,no.print.fields = "issn"))
  cat("\n")
}

```


# Refereed Articles en Français *(`r art_nb_FR`)*

```{r echo=FALSE, results="asis",comment=FALSE}
file_journals <- file_journals_FR
dates <- unlist(unique(file_journals$year))[order(unlist(unique(file_journals$year)),decreasing = TRUE)]


#Prints references
for (date in dates) {
  cat(paste0("## ",date),"\n")
  print(file_journals[list(year=date)],.opts = list(style="markdown",bib.style ="authoryear" ,max.names =20,dashed=FALSE,no.print.fields = "issn"))
  cat("\n")
}

```
